data = [
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'Bradford, England',
    },
    {
        'artist': 'Harry Styles',
        'followers': 1,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'Redditch, UK',
    },
    {
        'artist': 'Louis Tomlinson',
        'followers': 2,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'Doncaster, UK',
    },
    {
        'artist': 'Liam Payne',
        'followers': 3,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'Wolverhampton, UK',
    },
    {
        'artist': 'Niall Horan',
        'followers': 4,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'Mullingar, Ireland',
    },
    {
        'artist': 'Selena Gomez',
        'followers': 5,
        'occupation': 'Musician',
        'born': 'Texas, UK',
    },
    {
        'artist': 'Taylor Swift',
        'followers': 6,
        'occupation': 'Musician',
        'born': 'Pennsylvania, US',
    },
    {
        'artist': 'Gigi Hadid',
        'followers': 7,
        'occupation': 'Model',
        'born': 'California, US',
    },
    {
        'artist': 'Kendall Jenner',
        'followers': 8,
        'occupation': 'Model',
        'born': 'California, US',
    },
    {
        'artist': 'Kylie Jenner',
        'followers': 9,
        'occupation': 'Model',
        'born': 'California, US',
    },
    {
        'artist': 'Chris Brown',
        'followers': 10,
        'occupation': 'Musician',
        'born': 'Virginia, US',
    },
    {
        'artist': 'Chris Pratt',
        'followers': 11,
        'occupation': 'Actor',
        'born': 'Minnesota, US',
    },
    {
        'artist': 'Zac Efron',
        'followers': 12,
        'occupation': 'Actor',
        'born': 'California, US',
    },
    {
        'artist': 'Ed Sheeran',
        'followers': 13,
        'occupation': 'Musician',
        'born': 'Halifax, UK',
    },
    {
        'artist': 'instagram',
        'followers': 14,
        'occupation': 'verified account',
        'born': 'unknown',
    },
    {
        'artist': 'Perrie Edwards',
        'followers': 15,
        'occupation': 'Musician',
        'born': 'South Shields, UK',
    },
    {
        'artist': 'NASA',
        'followers': 16,
        'occupation': 'verified account',
        'born': 'unknown',
    },
    {
        'artist': 'folkative',
        'followers': 17,
        'occupation': 'verified account',
        'born': 'unknown',
    },
    {
        'artist': 'Marshmello',
        'followers': 18,
        'occupation': 'Musician',
        'born': 'Pennsylvania, US',
    },
    {
        'artist': 'Camila Cabello',
        'followers': 19,
        'occupation': 'Musician',
        'born': 'Cojimar, Cuba',
    },
    {
        'artist': 'Shawn Mendes',
        'followers': 20,
        'occupation': 'Musician',
        'born': 'Pickering, Canada',
    },
    {
        'artist': 'Alan Walker',
        'followers': 21,
        'occupation': 'Musician',
        'born': 'Northampton, UK',
    },
    {
        'artist': 'Imagine Dragons',
        'followers': 22,
        'occupation': 'Musician',
        'born': 'Las Vegas, Nevada',
    },
    {
        'artist': 'Lady Gaga',
        'followers': 23,
        'occupation': 'Musician, Actor',
        'born': 'New York, US',
    },
    {
        'artist': 'Ariana Grande',
        'followers': 24,
        'occupation': 'Musician',
        'born': 'Florida, US',
    }
]
