data = [
    {
        'artist': 'first',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'Zayn Malik',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    },
    {
        'artist': 'last',
        'followers': 51503966,
        'occupation': 'Musician, One Direction Former Member',
        'born': 'England',
    }
]
